name: CI

on:
  push:
    branches: [ "*" ]
    paths-ignore:
    - '**.md'
  pull_request:

  workflow_dispatch:

jobs:
  helloworld:
    name: "Hello world Flatpak example"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@master
      with:
        bundle: flatpak.ocaml.example.flatpak
        manifest-path: flatpak.ocaml.example.yaml
        cache-key: flatpak-builder-${{ github.sha }}

  labgtk:
    name: "Labgtk built from sources Flatpak example"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@master
      with:
        bundle: flatpak.ocaml.lablgtk.build.flatpak
        manifest-path: flatpak.ocaml.lablgtk.build.yaml
        cache-key: flatpak-builder-${{ github.sha }}
